models/applicant.py
#!/usr/bin/env python3

# Import
from app import db
from datetime import datetime
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship
from werkzeug.security import generate_password_hash, check_password_hash


class Applicant(db.Model):
    """
    A class that defines the Applicant Credentials
    """

    __tablename__ = "applicants"
    email = db.Column(db.String(255), primary_key=True, unique=True, nullable=False)
    phonenumber = db.Column(db.String(11), nullable=False)
    password = db.Column(db.String(255), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(
        db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )
    is_paid = db.Column(db.Boolean, default=datetime.utcnow)

    # Relationship with Admission form
    applicant_number = db.relationship("AdmissionForm", backref="applicants")

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

models/special.py
#!/usr/bin/python3


# Import
from app import db
from datetime import datetime
import re
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship
from werkzeug.security import generate_password_hash, check_password_hash


class Specialadmin(db.Model):
    __tablename__ = "specialadmin"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True, nullable=False)
    email = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(
        db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    # A validation check for email format using python library 'validate_email'
    def validate_email(self, email):
        """
        define a re expression for a simple email format check
        """
        email_pattern = r"^[\w\.-]+@[\w\.-]+\.\w+$"
        if not re.match(email_pattern, email):
            raise ValueError("Invalid email format")

controllers/pageroute.py
#!/usr/bin/env python3
from flask import (
    current_app,
    Blueprint,
    render_template,
    jsonify,
    request,
    url_for,
    session,
    redirect,
    send_file,
    send_from_directory,
    make_response,
    flash,
)
from functools import wraps
from config import UPLOAD_FOLDER, allowed_file
import json
import traceback
import base64
import requests
from urllib.parse import quote, unquote
import jwt
import logging
from io import BytesIO
from werkzeug.utils import secure_filename
from datetime import datetime, timedelta
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.exc import SQLAlchemyError
import os
import pymysql
from MySQLdb import OperationalError
from dotenv import load_dotenv
import time
import traceback
from models import (
    Student,
    Department,
    Semester,
    ContactMessage,
    Admin,
    AdmissionForm,
    FormImage,
    Newsletter,
    Specialadmin,
    Applicant,
    Image,
    Course,
    PaymentStatus,
)
from controllers import StudentScoreForm
from app import cache, db
from views import *


# Set up logging
logging.basicConfig(level=logging.DEBUG)


# /****************************************** GLOBAL ROUTES ************************************************/


pages_bp = Blueprint("pages", __name__, template_folder="templates")


# Load environment variables from the .env file
load_dotenv()


# Print loaded environment variables
print(os.getenv("PAYSTACK_SECRET_KEY"))


@pages_bp.route("/")
@cache.cached(timeout=500)
def home():
    """
    A route that handles the app homepage
    """

    image1 = os.path.join(current_app.config["UPLOAD_FOLDER"], "section-img.png")
    image2 = os.path.join(current_app.config["UPLOAD_FOLDER"], "slider.jpg")
    image3 = os.path.join(current_app.config["UPLOAD_FOLDER"], "student.webp")
    image4 = os.path.join(current_app.config["UPLOAD_FOLDER"], "sunnahlogo.avif")
    image5 = os.path.join(current_app.config["UPLOAD_FOLDER"], "sunPics1.webp")
    image6 = os.path.join(current_app.config["UPLOAD_FOLDER"], "sunPics2.webp")
    # image7 = os.path.join(app.config['UPLOAD_FOLDER'], 'icon-close.svg')
    return render_template(
        "homepage.html",
        user_image=image1,
        user_image2=image2,
        user_image3=image3,
        user_image4=image4,
        user_image5=image5,
        user_image6=image6,
    )


# /****************************************** VIEWS ROUTES ************************************************/


# /****************************************** STUDENT LOGIN & LOGIC ROUTES ************************************************/


@pages_bp.route("/payment_callback", methods=["GET"])
def paymentCallback():
    reference = request.args.get("reference")
    logging.debug("Reference: %s", reference)

    if not reference:
        logging.error("No reference provided")
        return "No reference provided", 400

    # Verify User payment
    try:
        response = requests.get(
            f"https://api.paystack.co/transaction/verify/{reference}",
            headers={"Authorization": f"Bearer {os.getenv('PAYSTACK_SECRET_KEY')}"},
        )
        logging.debug("Paystack Response: %s", response.text)
    except requests.RequestException as e:
        logging.error("RequestException during Paystack verification: %s", e)
        return "Failed to verify payment with Paystack", 500

    if response.status_code == 200:
        data = response.json().get("data", {})
        status = data.get("status")
        if status == "success":
            customer = data.get("customer", {})
            email = customer.get("email")
            if email:
                logging.debug("Email: %s", email)

                # Store user payment credentials in session
                session["email"] = email
                session["is_paid"] = True

                # Check if the user already exists in the database
                user = PaymentStatus.query.filter_by(email=email).first()
                if user:
                    user.is_paid = True
                    db.session.commit()
                else:
                    # Create a new Paymentstatus if it doesn't exist
                    new_user = PaymentStatus(email=email, is_paid=True)
                    db.session.add(new_user)
                    db.session.commit()
                    logging.info("New PaymentStatus entry created for email: %s", email)

                return redirect(url_for("pages.applicant"))
            else:
                logging.error("Email not found in Paystack response")
                return "Email not found in Paystack response", 400
        else:
            logging.error("Payment verification failed: %s", status)
            return f"Payment verification failed: {status}", 400
    else:
        logging.error(
            "Failed to verify payment with Paystack, status code: %d",
            response.status_code,
        )
        return "Failed to verify payment with Paystack", 400


def payment_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        email = session.get("email")
        is_paid = session.get("is_paid")
        current_app.logger.debug(f"email in session: {email}, is_paid: {is_paid}")

        if not email or not is_paid:
            return redirect(url_for("pages.admission"))

        user = PaymentStatus.query.filter_by(email=email).first()

        if not user or not user.is_paid:
            current_app.logger.debug("User not found or not paid in database")
            return redirect(url_for("pages.payment_callback"))

        return f(*args, **kwargs)

    return decorated_function


@pages_bp.route("/store_payment_status", methods=["POST"])
def store_payment_status():
    data = request.json
    if "email" not in data or "is_paid" not in data:
        return jsonify({"error": "Email and is_paid fields are required"}), 400

    email = data["email"]
    is_paid = data["is_paid"]

    try:
        user = PaymentStatus.query.filter_by(email=email).first()
        if user:
            # Update the payment status if the user already exists
            user.is_paid = is_paid
        else:
            # Create a new user entry if the user doesn't exist
            user = PaymentStatus(email=email, is_paid=is_paid)
            db.session.add(user)

        db.session.commit()
        return jsonify({"message": "Payment status stored successfully"}), 200

    except Exception as e:
        db.session.rollback()
        logging.error("Error storing payment status: %s", e)
        return jsonify({"error": "Failed to store payment status"}), 500


@pages_bp.route("/login", methods=["POST"])
def login():
    """
    a route that handles students authentication
    """
    try:
        admission_number = request.form["admission_number"]
        password = request.form["password"]

        user = Student.query.filter_by(admission_number=admission_number).first()
        if user and user.check_password(password):
            """
            create a jwt token
            """
            token = jwt.encode(
                {
                    "user_id": user.admission_number,
                    "exp": datetime.utcnow()
                    + timedelta(hours=2),  # Token expiration Time
                },
                "secret_key",
                algorithm="HS256",
            )

            session["token"] = token  # Store token in the session
            session["user_id"] = user.admission_number  # Store user ID in the session

            return redirect(url_for("pages.dashboard"))
        else:
            flash("Incorrect admission number or password. Please try agin.", "danger")
            return redirect(url_for("pages.signinstudent"))
    except Exception as e:
        flash("An error occured: {}".format(str(e)), "danger"), 500
        return redirect(url_for("pages.signinstudent"))


# /****************************************** END OF HOMEPAGE & LOGIC ROUTES ************************************************/


# /****************************************** ADMIN ROUTES ************************************************/


@pages_bp.route("/admin", methods=["POST"])
def admin():
    """
    A route that handles admin authentication
    """
    try:
        email = request.form.get("email")
        password = request.form.get("password")

        if email is None or password is None:
            return jsonify({"error": "Email and password are required."}), 400

        user = Admin.query.filter_by(email=email).first()
        if user and user.check_password(password):
            """
            Create a JWT token
            """
            token = jwt.encode(
                {
                    "admin_user_id": user.email,
                    "exp": datetime.utcnow()
                    + timedelta(hours=2),  # Token expiration time
                },
                "secret_key",
                algorithm="HS256",
            )

            session["admin_token"] = token  # Store the token in the session
            session["admin_user_id"] = user.email  # Store user ID in the session

            return redirect(url_for("pages.admindash"))
        else:
            flash("Incorrect email or password. Please try agin.", "danger")
            return redirect(url_for("pages.signinadmin"))
    except Exception as e:
        traceback.print_exc()
        flash(f"An error occurred: {str(e)}", "danger"), 500
        return redirect(url_for("pages.signinadmin"))


# authenticate and authorize requests using JWT
def token_required(func):
    @wraps(func)
    def decorated(*args, **kwargs):
        token = request.headers.get("Authorization")

        if not token:
            return jsonify({"error": "Token is missing"}), 401

        try:
            data = jwt.decode(token, "secret_key", algorithms=["HS256"])
            current_user = Student.query.get(data["user_id"])
        except:
            return jsonify({"error": "Token is invalid"}), 401

templates/applicant_login_page.html
<!DOCTYPE html>
<html class="no-js" lang="zxx">
    <head>
        <!-- Meta Tags -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="keywords" content="Braham Health College">
		<meta name="description" content="Braham Health College Mararaba New Karu Nassarawa">
		<meta name='copyright' content=''>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		
		<!-- Title -->
        <title>Login - Braham Health College</title>
		
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

		<!-- Favicon -->
        <link rel="icon" href="{{ url_for('static', filename='img/favicon.png')}}">
		
		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
		<!-- Nice Select CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/nice-select.css')}}">
		<!-- Font Awesome CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css')}}">
		<!-- icofont CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/icofont.css')}}">
		<!-- Slicknav -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/slicknav.min.css')}}">
		<!-- Owl Carousel CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/owl-carousel.css')}}">
		<!-- Datepicker CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/datepicker.css')}}">
		<!-- Animate CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.min.css')}}">
		<!-- Magnific Popup CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/magnific-popup.css')}}">
		
		<!-- Medipro CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css')}}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css')}}">
        <!-- <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}"> -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css')}}">
		
    </head>
<body>
  <div class="container">
    <div class="side-by-side">
      <div class="image-container">
        <img src={{user_image4}} alt="School Logo">
      </div>
      <div class="card">
        <div class="mobile-img">
          <img src={{user_image4}} alt="School Logo">
        </div>
        <h2 class="mb-2">Sign In</h2>
        <p>Welcome to Braham Health College Portal | Login</p>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% set shown = false %}
            <div class="flash-messages">
                {% for category, message in messages %}
                    {% if not shown %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                        {% set shown = true %}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    
        <form action="/applicant_page" method="POST" id="applicantpage">
          <div class="group">
            <label for="email">Email</label>
            <input type="text" id="email" name="email" required>
          </div>
          <div class="group">
            <label for="password">Password</label>
            <input type="password" id="password" name="password" required>
          </div>

          <button type="submit" class="btn mt-2">Login</button>
        </form>
        <a href="#" class="forgot-password">Forgot password?</a>

        
        <div class="input-group home mt-2">
          <a href="{{ url_for('pages.home') }}" class=""><i class="larger-icon icofont-home"></i> Home</a>
          <a href="https://paystack.com/pay/3agbxw7--0" class=""><i class="larger-icon icofont-loop"></i> Register</a>
        </div>
      </div>
    </div>
  </div>
  <script src="script.js"></script>
</body>
</html>

templates/application.html
<!doctype html>
<html class="no-js" lang="zxx">
    <head>
        <!-- Meta Tags -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="keywords" content="Braham Health College">
		<meta name="description" content="Braham Health College Mararaba New Karu Nassarawa">
		<meta name='copyright' content=''>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		
		<!-- Title -->
        <title>Application - Braham Health College</title>

		
		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
		
		<!-- Favicon -->
        <link rel="icon" href="{{ url_for('static', filename='img/favicon.png')}}">
		
		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
		<!-- Nice Select CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/nice-select.css')}}">
		<!-- Font Awesome CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css')}}">
		<!-- icofont CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/icofont.css')}}">
		<!-- Slicknav -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/slicknav.min.css')}}">
		<!-- Owl Carousel CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/owl-carousel.css')}}">
		<!-- Datepicker CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/datepicker.css')}}">
		<!-- Animate CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.min.css')}}">
		<!-- Magnific Popup CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/magnific-popup.css')}}">
		
		<!-- Medipro CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css')}}">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css')}}">
		
    </head>
    <body>

	
		<!-- Header Area -->
		<header class="header" >
			<!-- Topbar -->
			<div class="topbar">
				<div class="container">
					<div class="row">
						<div class="col-lg-6 col-md-5 col-12">
							<!-- Contact -->
							<ul class="top-link">
								<li><a href="{{ url_for('pages.contact') }}">Contact</a></li>
							</ul>
							<!-- End Contact -->
						</div>
						<div class="col-lg-6 col-md-7 col-12">
							<!-- Top Contact -->
							<ul class="top-contact">
								<li><i class="fa fa-phone"></i>+234 8082 147 327</li>
                                <li><i class="fa fa-envelope"></i><a href="mailto:support@yourmail.com">support@Brahamhealthcollege.com</a></li>
							</ul>
							<!-- End Top Contact -->
						</div>
					</div>
				</div>
			</div>
			<!-- End Topbar -->
			<!-- Header Inner -->
			<div class="header-inner">
				<div class="container">
					<div class="inner">
						<div class="row">
							<div class="col-lg-3 col-12">
								<!-- Start Logo -->
								<div class="logo">
									<a href="{{ url_for('pages.home') }}"><img src={{user_image4}}></a>
								</div>
								<!-- End Logo -->



			<!-- Mobile Nav -->
			<div class="mobile-nav">
			
				
				
						</div>
						<!-- End Mobile Nav -->
				
				

							
							</div>
							<div class="links col-lg-7 col-md-9 col-12 ">
								<!-- Main Menu -->
								<div class="main-menu">
									<nav class="navigation ">
										<ul class="nav menu">
											<li class="active"><a href="{{ url_for('pages.home') }}">Home </a>
											</li>
											<li><a href="#">About Us <i class="icofont-rounded-down"></i></a>
											<ul class="dropdown">
													<li><a href="{{ url_for('pages.vision') }}">Vision, Mission and Core Value</a></li>
													<li><a href="{{ url_for('pages.history') }}">Brief History</a></li>
												</ul>
											</li>
											<li><a href="{{ url_for('pages.programmes') }}">Programmes </a>
											</li>
												<li><a href="{{ url_for('pages.admission') }}">Admission </a></li>

											<li><a href="{{ url_for('pages.contact') }}">Contact Us</a></li>

											<a href="{{ url_for('pages.signinstudent') }}" class="mobile-btn">Portal</a>
										</ul>

										

									</nav>
								</div>
								<!--/ End Main Menu -->
							</div>
							<div class="apply col-lg-2 col-12">
								<div class="get-quote">
									<a href="{{ url_for('pages.signinstudent') }}" class="btn portal">Portal</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--/ End Header Inner -->
		</header>
		<!-- End Header Area -->

		<!-- Breadcrumbs -->
		<div class="breadcrumbs overlay">
			<div class="container">
				<div class="bread-inner">
					<div class="row">
						<div class="col-12">
							<h2>Application Form Portal</h2>
							<ul class="bread-list">
								<li><a href="{{ url_for('pages.home') }}">Home</a></li>
								<li><i class="icofont-simple-right"></i></li>
								<li class="active">Application Form (Registration Page)</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Breadcrumbs -->
	
		<!-- Start Portfolio Details Area -->
		<section class="pf-details section">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="inner-content">
						
				
							<div class="body-text">
								<h6>
                                    Registration Steps
                                </h6>

                                <p><i class="fa fa-long-arrow-right"></i>  Register an Account on this page. The Email Address and phone number supplied has to be unique, and will serve as your Registration ID to make payment</p>
                                <p><i class="fa fa-long-arrow-right"></i>  The name provided must be the real name of the applicant</p> 
								<p><i class="fa fa-long-arrow-right"></i>  If you have previously registered but yet to make payment, <a style="color: blue;" href="https://paystack.com/pay/p0yak43zos">click here to login.</a> </p>
                                <!-- <p><i class="fa fa-long-arrow-right"></i>  If you have previously registered but yet to make payment, <a style="color: blue;" href="https://paystack.com/pay/3agbxw7--0">click here to login.</a> </p> -->
								<div class="share">
									<h4>Share Now -</h4>
									<ul>
										<li><a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
										<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End Portfolio Details Area -->
		
		
			
		<!-- Footer Area -->
		<footer id="footer" class="footer ">
			<!-- Footer Top -->
			<div class="footer-top">
				<div class="container">
					<div class="row">
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer">
								<h2>About Us</h2>
								<p>We are dedicated to fostering 
									a tradition of excellence in providing top-notch education
									 and unparalleled services in the fields of science, health, and technology.</p>
								<!-- Social -->
								<ul class="social">
									<li><a href="#"><i class="icofont-facebook"></i></a></li>
									<li><a href="#"><i class="icofont-instagram"></i></a></li>
									<li><a href="#"><i class="icofont-twitter"></i></a></li>
                                    <li><a href="#"><i class="icofont-youtube-play"></i>
                                    </a></li>
								</ul>
								<!-- End Social -->
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer f-link">
								<h2>Quick Links</h2>
								<div class="row">
									<div class="col-lg-6 col-md-6 col-12">
										<ul>
											<li><a href="{{ url_for('pages.home') }}"><i class="fa fa-caret-right" aria-hidden="true"></i>Home</a></li>
											<li><a href="{{ url_for('pages.history') }}"><i class="fa fa-caret-right" aria-hidden="true"></i>About Us</a></li>
											<li><a href="{{ url_for('pages.admission') }}"><i class="fa fa-caret-right" aria-hidden="true"></i>Admission</a></li>
											<li><a href="{{ url_for('pages.vision') }}"><i class="fa fa-caret-right" aria-hidden="true"></i>why Braham</a></li>	
										</ul>
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<ul>
										
											<li><a href="{{ url_for('pages.programmes') }}"><i class="fa fa-caret-right" aria-hidden="true"></i>Programmes</a></li>
											<li><a href="{{ url_for('pages.contact') }}"><i class="fa fa-caret-right" aria-hidden="true"></i>Contact Us</a></li>	
										</ul>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer">
								<h2>Open Hours</h2>
								<ul class="time-sidual">
									<li class="day">Monday - Friday <span>8:00-5:00pm</span></li>
									<li class="day">Saturday <span>9:00-12:30pm</span></li>
								</ul>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer">
								<h2>Newsletter</h2>
								<p>Sign up for our newsletter to stay connected and receive the latest updates, news, and insights from Braham College of Health, Science, and Technology.</p>
								<form action="/newsletter" method="post" class="newsletter-inner" id="newsletter">
									<input name="email" id="email" placeholder="Your email address" class="common-input" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your email address'" required=""  type="text">
									<button class="button"  alt="subscription button" aria-label="link to subscrible to out daily notification" type="submit"><i class="icofont icofont-paper-plane"></i></button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--/ End Footer Top -->
			<!-- Copyright -->
			<div class="copyright">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-12">
							<div class="copyright-content">
								<p>© Copyright 2023  |  All Rights Reserved.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--/ End Copyright -->
		</footer>
		<!--/ End Footer Area -->



			
		<script>
			$(document).ready(function () {
				$('.newsletter-inner').submit(function (e) {
					e.preventDefault(); // Prevent form submission
					var formData = {
						email: $(this).find('.common-input').val()
					};
					var url = $(this).attr('action'); // Get the form's action URL
					$.ajax({
						type: 'POST',
						url: url,
						contentType: 'application/json',
						data: JSON.stringify(formData),
						success: function (response) {
							// Handle success response
							alert(response.message);
							location.reload(); // Reload the page
						},
						error: function (xhr, status, error) {
							// Handle error response
							console.error(error);
							alert("An error occurred while sending your message. Please try again later.");
						}
					});
				});
			});
		</script>


		<!-- jquery Min JS -->
        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery-migrate-3.0.0.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery-ui.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/easing.js') }}"></script>
        <script src="{{ url_for('static', filename='js/colors.js') }}"></script>
        <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap-datepicker.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.nav.js') }}"></script>
        <script src="{{ url_for('static', filename='js/slicknav.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.scrollUp.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/niceselect.js') }}"></script>
        <script src="{{ url_for('static', filename='js/tilt.jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/owl-carousel.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.counterup.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/steller.js') }}"></script>
        <script src="{{ url_for('static', filename='js/wow.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.magnific-popup.min.js') }}"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    </body>
</html>